name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install dev dependencies
        run: |
          pip install mypy coverage flake8 pre-commit
      
      - name: Static type checking
        run: |
          mypy deepseek_mlops
      
      - name: Run tests
        run: |
          pytest  # Projenize uygun test komutunu çalıştırın.
      
      - name: Run coverage
        run: |
          coverage run -m pytest
          coverage report
      
      - name: Docker build and run
        run: |
          docker build -t deepseek .
          docker run --rm deepseek
      
      - name: Pre-commit checks
        run: |
          pre-commit run --all-files